const properties = {
  123: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
  456: {
    location: "Lake Sevilla, TX",
    price: 500,
    type: "Villas",
    name: "Beverly Springfield",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "2.jpg",
  },
  2: {
    location: "Michigan, IN",
    price: 500,
    type: "Flats",
    name: "Faulkner Ave",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "3.jpg",
  },
  3: {
    location: "Krishna Park, India",
    price: 500,
    type: "Houses",
    name: "Parmeshwar",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "4.jpg",
  },
  34: {
    location: "Sundar Nagar, India",
    price: 500,
    type: "Flats",
    name: "Glory Hills",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "5.jpg",
  },
  23: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
  100: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "3.jpg",
  },
  121: {
    location: "Mumbai, India",
    price: 500,
    type: "Villas",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "4.jpg",
  },
  129: {
    location: "New York, USA",
    price: 500,
    type: "Villas",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "5.jpg",
  },
  190: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Ambani Villa",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
  1323: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
  1232: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
  12311: {
    location: "New York, USA",
    price: 500,
    type: "Houses",
    name: "Palm Harbour",
    beds: 3,
    bathrooms: 2,
    area: "5*7 m2",
    image: "1.jpg",
  },
};
export default properties;
